FROM caddy:{{ .config.caddy_version }}-builder AS builder

RUN xcaddy build \
    --with github.com/mholt/caddy-dynamicdns \
    --with github.com/caddy-dns/godaddy \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2

FROM caddy:{{ .config.caddy_version }}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]