name: Docker Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-linux-build:
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: caddy-godaddy
      DOCKER_BUILDKIT: '1'
    steps:
      - uses: actions/checkout@master
      - name: non-master build test
        run: |
          docker build -f 2.8/alpine/Dockerfile 2.8/alpine
        if: github.repository != 'davejab/caddy-godaddy-docker' || github.ref != 'refs/heads/main'
      - name: build
        run: bashbrew build caddy-godaddy
      - name: push
        # NOTE: DOCKERHUB_TOKEN and DOCKERHUB_USERNAME must be present in https://github.com/davejab/caddy-godaddy-docker/settings
        # the user must have permission to push to https://hub.docker.com/r/davejabra/caddy-godaddy
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          bashbrew push caddy-godaddy
        if: github.repository == 'davejab/caddy-godaddy-docker' && github.ref == 'refs/heads/main'
      - name: push (non-master dry run)
        run: |
          bashbrew push --dry-run caddy-godaddy
        if: github.repository != 'davejab/caddy-godaddy-docker' || github.ref != 'refs/heads/main'
